version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - filestore-net

  server:
    stdin_open: true
    tty: true 
    build:
      context: ./server
    ports:
      - "8080:80"
    networks:
      - filestore-net

networks:
  filestore-net:
    driver: bridge