version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - filestore-net

  server:
    privileged: true
    stdin_open: true
    tty: true 
    cap_add:
      - ALL
    build:
      context: ./server
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - filestore-net

networks:
  filestore-net:
    driver: bridge