version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock